[versions]
agp = "9.0.1"
kotlin = "2.3.10"

coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"

datastore = "1.2.0"
coroutines = "1.10.2"

lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.4"
navigationCompose = "2.9.7"
workRuntimeKtx = "2.11.1"

composeBom = "2026.02.00"

room = "2.8.4"

hilt = "2.59.1"
hilt-navigation-compose = "1.3.0"
ksp = "2.3.5"

junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

gson = "2.13.2"
okhttp = "5.3.2"
coreSplashscreen = "1.2.0"
graphicsShapes = "1.1.0"

firebase-bom = "34.9.0"
firebase-messaging = "25.0.1"
crashlytics-gradle = "3.0.6"

google-services = "4.4.4"
play-services-location = "21.3.0"
google-fonts-compose = "1.10.3"

materialKolor = "4.1.1"

[libraries]
# Gradle
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }

# Core
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-graphics-shapes = { module = "androidx.graphics:graphics-shapes", version.ref = "graphicsShapes" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

google-material = { module = "com.google.android.material:material", version.ref = "material" }

# LifeCycle
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

# Compose
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-text = { module = "androidx.compose.ui:ui-text" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-test-junit = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

compose-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "google-fonts-compose" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }

# Room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

# WorkManager
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }

# Testing
junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebase-messaging" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics-gradle" }
google-services-gradle = { module = "com.google.gms:google-services", version.ref = "google-services" }

# Misc
google-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
